StronaONiczym/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path("<series>", views.series, name="series"),
    path("<series>/<article>", views.article, name="article")
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('/register', views.register, name='register'),
]

main/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
# Create your models here.
class ArticleSeries(models.Model):
    title = models.CharField(max_length=300)
    subtitle = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=False, blank=False, default='')
    published = models.DateTimeField(default=timezone.now)
    class Meta:
        verbose_name_plural = "Series"
        ordering = ['-published']
    def __str__(self):
        return self.title
class Article(models.Model):
    title = models.CharField(max_length=300)
    subtitle = models.CharField(max_length=100, default='', blank=True)
    article_slug = models.SlugField(unique=True, null=False, blank=False, default='')
    content = HTMLField(blank=True, default='')
    notes = HTMLField(blank=True, default='')
    published = models.DateTimeField(default=timezone.now)
    modified = models.DateTimeField(default=timezone.now)
    series = models.ForeignKey(ArticleSeries, on_delete=models.SET_DEFAULT, default="", verbose_name="Series")
    class Meta:
        verbose_name_plural = "Article"
        ordering = ['-published']
    def __str__(self):
        return self.title
    @property
    def slug(self):
        return self.series.slug + "/" + self.article_slug

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class MyUser(AbstractUser):
    STATUS = (
        ('regular', 'regular'),
        ('entitled', 'entitled'),
        ('moderator', 'moderator'),
    )
    email = models.EmailField(unique=True)
    status = models.CharField(max_length=100, choices=STATUS, default='regular')
    description = models.TextField('description', max_length=700, default='', blank=True)
    def __str__(self):
        return self.username

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import get_user_model

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(help_text ="Enter email", required=True)
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')
    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()

        return user

main/views.py
from django.shortcuts import render
from .models import Article, ArticleSeries
# Create your views here.
def home(request):
    matching_series = ArticleSeries.objects.all()

    return render(request,
                  'main/home.html',
                  {'objects' : matching_series})
def series(request, series: str):
    matching_series = Article.objects.filter(series__slug=series).all()

    return render(request,
                  'main/home.html',
                  {'objects': matching_series})
def article(request, series: str, article: str):
    matching_article = Article.objects.filter(series__slug=series, article_slug=article).first()

    return render(request,
                  "main/article.html",
                  {'object':matching_article})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, login, logout
from .forms import UserRegistrationForm

# Create your views here.
def register(request):
    if request.user.is_authenticated:
        return redirect('main:home')
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main:home')
        for error in list(form.errors.values()):
            print(request, error)
    else:
        form = UserRegistrationForm()
    return render(
        request,
        'register.html',
        {'form': form}
    )

main/templates/main/article.html
{% extends "main/header.html" %}
{% block content %}
<div class="row media content-section mobiledevice">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="d-flex">
            <div>
                <h1 class="title-style">{{ object.title }}</h1>
                <h2 class="subtitle-style">{{ object.subtitle }}</h2>
            </div>
        </div>
    </div>
    <div class="col-lg-9 col-md-12 col-sm-12" id="content">
        <div class="article-style">
            {{ object.content|safe }}
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main/header.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Link to page favicon.ico to display in location Bar-->
    <link rel="icon" href="{% static 'images/favicon.png' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!-- reference to your installed Font Awesome Free package's files here -->
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'main/main.css' %}">

    <!-- Jquery JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>
<body>
    {% include 'main/includes/navbar.html' %}
    <main role="main" class="container-xl">
        <div class="row">
            <div class="col-lg-12 col-md-12-p-0 col-sm-12">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>

    <!-- Prism JS -->
    <script src="{% static 'prism.js' %}"></script>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>

    <!-- Optional JavaScript -->
    <script type="text/javascript" src="{% static 'main/custom.js' %}"></script>
</body>
</html>

main/templates/main/home.html
{% extends "main/header.html" %}
{% block content %}
    <div class="row display-flex justify-content-start">
    {% for object in objects %}
        <div class="col-lg-4 col-md-6 col-sm-12 mobiledevice">
            <article class="media content-section customhover" style="height: 95%;">
                <div class="media-body">
                    <a href="/{{object.slug}}">
                        <img class="img-fluid" src="/">
                    </a>
                    <div>
                        <a class="article-title line-clamp-2 title-style" style="font-size: 22px" href="/{{object.slug}}">
                            {{ object.title }}
                        </a>
                        <a href="/{{object.slug}}" style="text-decoration: none;">
                            <p class="article-content line-clamp-5 subtitle-style">{{ object.subtitle }}</p>
                        </a>
                    </div>
                </div>
            </article>
        </div>
    {% endfor %}
    </div>
{% endblock content %}

main/templates/main/includes/navbar.html
<header class="site-header" style="margin-bottom: 5px">
    <nav class="navbar navbar-expand-md navbar-color">
        <div class="container">
            <!-- Navbar Left Side -->
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="/">Home</a>
            </div>
            <button aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler ml-auto float-right btncolor" data-target="#navbarToggle" data-toggle="collapse" type="button">
                <i class="fas fa-bars fa-2x"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <!-- Navbar Left Side -->
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="/">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="/">
                        Log in <i class="fas fa-sign-in-alt"></i>
                    </a>
                    <a class="nav-item nav-link" href="{% url 'users:register' %}">
                        Sign up <i class="fas fa-user-plus"></i>
                    </a>
                </div>
            </div>
        </div>
    </nav>
</header>

templates/header.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Link to page favicon.ico to display in location Bar-->
    <link rel="icon" href="{% static 'images/favicon.png' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!-- reference to your installed Font Awesome Free package's files here -->
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'main/main.css' %}">

    <!-- Jquery JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>
<body>
    {% include 'main/includes/navbar.html' %}
    <main role="main" class="container-xl">
        <div class="row">
            <div class="col-lg-12 col-md-12-p-0 col-sm-12">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>

    <!-- Prism JS -->
    <script src="{% static 'prism.js' %}"></script>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>

    <!-- Optional JavaScript -->
    <script type="text/javascript" src="{% static 'main/custom.js' %}"></script>
</body>
</html>

users/templates/register.html
{% extends "main/header.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>

            By registering, you accept the Terms of Service and Privacy Notice

            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="/login">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}